WITH cte AS (
  SELECT 
    PUBLIC_HOUSING_AGENCY_NAME,
    INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS,
    LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE) AS PREVIOUS_INSPECTION_COST,
    LAG(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE) AS PREVIOUS_INSPECTION_DATE
  FROM public_housing_inspection_data
), cte2 AS (
  SELECT 
    PUBLIC_HOUSING_AGENCY_NAME,
    INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS,
    PREVIOUS_INSPECTION_COST,
    PREVIOUS_INSPECTION_DATE,
    ((COST_OF_INSPECTION_IN_DOLLARS - PREVIOUS_INSPECTION_COST) / PREVIOUS_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST,
    ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS RN
  FROM cte
  WHERE PREVIOUS_INSPECTION_COST IS NOT NULL
), cte3 AS (
  SELECT 
    PUBLIC_HOUSING_AGENCY_NAME As PHA_MR,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
    PREVIOUS_INSPECTION_DATE AS SECOND_MR_INSPECTION_DATE,
    PREVIOUS_INSPECTION_COST AS SECOND_MR_INSPECTION_COST,
    PERCENT_CHANGE_IN_COST
  FROM cte2
  WHERE RN = 1 AND PERCENT_CHANGE_IN_COST > 0
), cte4 AS (
  SELECT DISTINCT 
    PHA_MR,
    MR_INSPECTION_DATE,
    MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    PERCENT_CHANGE_IN_COST
  FROM cte3
)
SELECT 
  cte4.PHA_MR,
  cte4.MR_INSPECTION_DATE,
  cte4.MR_INSPECTION_COST,
  cte4.SECOND_MR_INSPECTION_DATE,
  cte4.SECOND_MR_INSPECTION_COST,
  cte4.PERCENT_CHANGE_IN_COST
FROM cte4
JOIN (
  SELECT PUBLIC_HOUSING_AGENCY_NAME
  FROM public_housing_inspection_data
  GROUP BY PUBLIC_HOUSING_AGENCY_NAME
  HAVING COUNT(*) > 1
) AS cte5 ON cte4.PHA_MR = cte5.PUBLIC_HOUSING_AGENCY_NAME
ORDER BY cte4.PERCENT_CHANGE_IN_COST DESC;